tonybaloney/Pyjion

.github/workflows/master.yml
CMakeLists.txt
Tests/python_bad_tests.txt
Tests/python_tests_macos10.txt
Tests/python_tests_macos11.txt
Tests/python_tests_win.txt
pyjion/intrins.cpp
pyproject.toml

Should address the issue with multithreaded tests

Take the GIL before calling function objects

---

pyjion/__init__.py

Locate system-wide installation of .NET 5

---

pyjion/jitinfo.h

Fix bad log file

---

src/pyjion/intrins.cpp

Fix the checking of dictionary/mapping types for the update and merge operations

---

CMakeLists.txt
src/pyjion/codemodel.h
src/pyjion/intrins.cpp
src/pyjion/jitinfo.h
src/pyjion/pyjit.cpp

Also fix/resolve the GS cookie

Remove verbose trace dumps now that tracing works

---

.github/workflows/master.yml
CMakeLists.txt
CMakeOptimizations.txt
Tests/test_emission.cpp
src/pyjion/dis.py
src/pyjion/helpers.asm
src/pyjion/ilgen.h
src/pyjion/ipycomp.h
src/pyjion/jitinfo.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Implement OPT-2

---

.devcontainer/devcontainer.json
.github/workflows/master.yml
.gitignore
CMakeLists.txt
CMakeOptimizations.txt
Dockerfile
Tests/Tests.cpp
Tests/test_basics.cpp
Tests/test_compiler.cpp
Tests/test_functions.py
Tests/test_imports.py
Tests/test_recursion.py
src/pyjion/absint.cpp
src/pyjion/dis.py
src/pyjion/exceptions.h
src/pyjion/ilgen.h
src/pyjion/intrins.cpp
src/pyjion/intrins.h
src/pyjion/ipycomp.h
src/pyjion/jitinfo.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Fix guard stack exceptions (fast_fail)

---

CMakeOptimizations.txt
Docs/source/opt/opt-4.rst
Docs/source/optimizations.rst
Tests/test_basics.cpp
Tests/test_compiler.cpp
Tests/test_exceptions.cpp
Tests/test_locals.py
Tests/test_scopes.cpp
Tests/test_tracing.cpp
src/pyjion/absint.cpp
src/pyjion/ilgen.h
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Implement OPT-4

---

CMakeOptimizations.txt
Docs/source/opt/opt-5.rst
Docs/source/optimizations.rst
Tests/test_basics.cpp
src/pyjion/pycomp.cpp
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Implement OPT-5

---

src/pyjion/absint.cpp

Fixes #47 
Known as FAST_DISPATCH in CPython

Skip lasti update on other opcodes

---

CMakeLists.txt

Fix windows build issue

---

CMakeLists.txt
Tests/test_inference.cpp
Tests/testing_util.cpp
src/pyjion/absint.cpp
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h

Work on opcode type inference for unary and binary operations of known types.
Add iterable as known type.

Type inference enhancements

---

.github/workflows/master.yml
CMakeLists.txt
Tests/python_smoke_tests.txt
Tests/runlibregr.py
Tests/test_dis.py
Tests/test_functions.py
Tests/test_imports.py
Tests/test_info.py
Tests/test_interns.py
Tests/test_lists.py
Tests/test_locals.py
Tests/test_recursion.py
Tests/test_tracing.py
Tests/test_tuples.py
Tests/test_types.py
src/pyjion/absint.cpp
src/pyjion/intrins.cpp
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h

- Fix the CI process to run the test suite properly (its not running it at all right now)

Build a test runner to execute the CPython test suite with isolated JIT tracing

---

src/pyjion/intrins.cpp

Implement PEP590 vector call in MethCallN

---

Tests/test_functions.py

Add tests for reference leaks in function and method calls with exceptions

---

Tests/test_compiler.cpp
src/pyjion/absint.cpp

Fix JUMP_IF_FALSE_OR_POP opcode stack effect

---

Tests/test_inference.cpp
Tests/test_interns.py
Tests/testing_util.cpp
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/intrins.cpp
src/pyjion/pyjit.cpp

Builtin functions will return known types

---

CMakeOptimizations.txt
Docs/source/opt/opt-9.rst
Docs/source/optimizations.rst
Tests/benchmarks/test_nbody.py
Tests/test_basics.cpp
Tests/test_interns.py
Tests/test_lists.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/absvalue.h
src/pyjion/dis.py
src/pyjion/ilgen.h
src/pyjion/intrins.cpp
src/pyjion/intrins.h
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Inline iterators

---

.github/workflows/master.yml
Tests/benchmarks/test_fannkuch.py
Tests/run_libregr_tests.py
Tests/run_smoke_tests.py
Tests/test_math.py
Tests/test_types.py
src/pyjion/absint.cpp
src/pyjion/intrins.cpp
src/pyjion/pyjitmath.cpp

Modulus opt8

---

.github/workflows/master.yml
Tests/benchmarks/test_fannkuch.py
Tests/run_libregr_tests.py
Tests/run_smoke_tests.py
Tests/test_math.py
Tests/test_types.py
src/pyjion/absint.cpp
src/pyjion/intrins.cpp
src/pyjion/pyjitmath.cpp

Link issues as they come up until the smoke tests are passing.

Reintroduce the test suites

---

src/pyjion/pyjitmath.cpp

Correct the number sequence for power as the second opcode

---

Tests/test_iterators.py
src/pyjion/absint.cpp

Fix a bug with the inline iterator when the iterator is a unpacked tuple

---

CHANGELOG.md
CMakeOptimizations.txt
Docs/source/opt/opt-10.rst
Docs/source/optimizations.rst
Tests/test_globals.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/dis.py
src/pyjion/intrins.cpp
src/pyjion/intrins.h
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Precompute all hashes for co_names in the code object and create an optimized path for LOAD_NAME.
Could be applied to LOAD_GLOBAL as well...

Optimize the LOAD_NAME opcode

---

src/pyjion/absvalue.cpp
src/pyjion/absvalue.h

Implement ByteArrayValue

---

src/pyjion/absvalue.cpp
src/pyjion/absvalue.h

Implement TypeValue

---

Tests/test_attr.py

Test for reference leaks in `getattr` and `setattr`

---

src/pyjion/absint.cpp
src/pyjion/absint.h

Move the f_lasti update to the failure branch

---

.github/workflows/benchmark.yml
Tests/benchmarks/test_chaos.py
Tests/benchmarks/test_django_template.py
Tests/benchmarks/test_fannkuch.py
Tests/benchmarks/test_float.py
Tests/benchmarks/test_nqueens.py
Tests/benchmarks/test_xml_etree.py

Create a seperate CI job for benchmarks, add a django template benchmark

---

.github/workflows/benchmark.yml
.github/workflows/master.yml
Tests/test_threads.py
src/pyjion/absint.cpp
src/pyjion/dis.py
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h

Remove backward loop calls to the periodic work function

---

src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/pyjit.cpp

Move GetAbstractType helper to absvalue

---

CMakeOptimizations.txt
Tests/test_basics.cpp
Tests/test_inference.cpp
Tests/test_methods.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/intrins.cpp
src/pyjion/intrins.h
src/pyjion/ipycomp.h
src/pyjion/pycomp.cpp
src/pyjion/pycomp.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Opt builtin methods

---

CHANGELOG.md
Tests/test_basics.cpp
Tests/test_inference.cpp
Tests/testing_util.cpp
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/knownmethods.h
src/pyjion/stack.h

Oversize stack

---

src/pyjion/absvalue.cpp
src/pyjion/absvalue.h

Closes #148 
Closes #147 
Closes #146

Implement missing types

---

Tests/test_interns.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/pyjit.cpp

Initialize states for all locals

---

Tests/test_dict.py
Tests/test_lists.py

Test for reference leaks in list and dict creation

---

src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/block.h
src/pyjion/exceptionhandling.cpp
src/pyjion/exceptionhandling.h
src/pyjion/pyjit.h
src/pyjion/stack.h

This'll clean up some of the warnings that CI is giving right now. There are still quite a few places that can be fixed up that aren't being reported on right now, but that can be done as part of a later clean-up.

Remove some warnings

---

Tests/test_compiler.cpp
src/pyjion/pycomp.cpp

Further fixes to UNPACK_SEQUENCE

---

Tests/test_pgc.cpp
src/pyjion/absint.cpp

Remove COMPARE_OP PGC probe

---

Tests/benchmarks/test_nbody.py
src/pyjion/absint.cpp
src/pyjion/pycomp.cpp

Implement PGC for UNPACK_SEQUENCE

---

CMakeLists.txt
Tests/benchmarks/test_nbody.py
Tests/test_compiler.cpp
Tests/test_pgc.cpp
Tests/test_pgc.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/pycomp.cpp
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Correct the PGC stack sequencing when the stack is bigger than the requested probe size

Fix a bug in PGC stack adjustments

---

.github/workflows/master.yml
Tests/requirements_test.txt
Tests/test_attr.py
Tests/test_binary.py
Tests/test_dis.py
Tests/test_flask.py
Tests/test_floats.py
Tests/test_functions.py
Tests/test_pgc.py
Tests/test_slice.py
Tests/test_strings.py
setup.py
src/pyjion/__init__.py
src/pyjion/absvalue.h
src/pyjion/pycomp.cpp
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Fix a crash on PGC compilation for freed last observed value

---

CHANGELOG.md
Docs/source/opt/opt-16.rst
Tests/test_math.cpp
setup.py
src/pyjion/__init__.py
src/pyjion/absint.cpp
src/pyjion/absint.h
src/pyjion/absvalue.h
src/pyjion/instructions.cpp
src/pyjion/pycomp.cpp
src/pyjion/pyjit.cpp
src/pyjion/unboxing.cpp

Unbox boolean values

---

.github/workflows/master.yml
CHANGELOG.md
Tests/hello.py
src/pyjion/__init__.py
src/pyjion/__main__.py

Add a runpy entrypoint

---

.github/workflows/benchmark.yml
Tests/benchmarks/test_spectralnorm.py
Tests/test_exceptions.cpp
Tests/test_pickle.py
Tests/test_types.py
src/pyjion/intrins.cpp

Fixes #301 
Fixes #290
Fixes #289

Add a pickle test and a spectral norm benchmark

---

Tests/requirements_test.txt
Tests/test_class.cpp
Tests/test_numpy.py
Tests/test_pyyaml.py
src/pyjion/absint.cpp
src/pyjion/binarycomp.cpp

Fix pyyaml decoding on PGC compile

---

Tests/test_basics.cpp
src/pyjion/knownmethods.h

Correct the ord() asserted return type

---

CHANGELOG.md
src/pyjion/__init__.pyi
src/pyjion/dis.py

Fix the native disassembler double line break

---

.github/workflows/master.yml
CHANGELOG.md
Docs/source/api.rst
Docs/source/index.rst
README.md
setup.py
src/pyjion/__main__.py

Implement a better Pyjion CLI

---

CHANGELOG.md
CMakeLists.txt
Tests/python_smoke_tests.txt
Tests/test_types.py
setup.py
src/pyjion/__init__.py
src/pyjion/intrins.cpp

Fix the crashing macOS test

---

CHANGELOG.md
src/pyjion/absint.cpp

LOAD_BUILD_CLASS will infer a function type instead of Any

---

Tests/test_basics.cpp
Tests/test_dict.py
Tests/test_generators.py
Tests/test_interns.py
Tests/test_lists.py
Tests/test_tracing.py
Tests/test_tuples.py
Tests/testing_util.h

Copy some of the C++ to the new pytest suite to improve coverage and catch PGC regressions

More unit tests

---

CHANGELOG.md
Tests/Tests.cpp
src/pyjion/absint.cpp
src/pyjion/instructions.cpp
src/pyjion/intrins.cpp
src/pyjion/pycomp.cpp
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h

Also fixes a bug in BINARY_SUBSCR at opt-level 0
Also fixes a bug in the new exception type

Conditional branches in instruction graph

---

CHANGELOG.md
Tests/benchmarks/bench_chaos.py
Tests/benchmarks/bench_deltablue.py
Tests/benchmarks/bench_django_template.py
Tests/benchmarks/bench_fannkuch.py
Tests/benchmarks/bench_float.py
Tests/benchmarks/bench_microbenchmarks.py
Tests/benchmarks/bench_nbody.py
Tests/benchmarks/bench_nqueens.py
Tests/benchmarks/bench_spectralnorm.py
Tests/conftest.py
Tests/test_inference.cpp
Tests/test_math.py
src/pyjion/__init__.py
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/instructions.cpp
src/pyjion/knownmethods.h
src/pyjion/pyjit.cpp
src/pyjion/pyjit.h
src/pyjion/unboxing.cpp
src/pyjion/unboxing.h

Math float miscalculation

---

CHANGELOG.md
Tests/test_pgc.cpp
src/pyjion/absint.cpp
src/pyjion/absvalue.cpp
src/pyjion/absvalue.h
src/pyjion/knownmethods.h

Pyjion will infer that `range(n)` generates integers in iterator to improve unboxing
